name: Docker 构建

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@main

      - name: 构建docker镜像
        run: |
          docker build -t formattoday/npm .

      - name: 推送docker镜像
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push formattoday/npm
