name: Docker 构建

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@main

      - name: 设置变量
        id: set_vars
        run: |
          image_name="formattoday/npm"
          current_time=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M%S')
          tag_local=${image_name}:local
          tag_latest=${image_name}:latest
          tag_time=${image_name}:${current_time}

          echo "tag_local=${tag_local}" >> $GITHUB_ENV
          echo "tag_latest=${tag_latest}" >> $GITHUB_ENV
          echo "tag_time=${tag_time}" >> $GITHUB_ENV

      - name: 构建docker镜像
        run: |
          docker build -t ${tag_local} .
          docker tag ${tag_local} ${tag_latest}
          docker tag ${tag_local} ${tag_time}

      - name: 推送docker镜像
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push ${tag_latest}
          docker push ${tag_time}